import React, { useState } from 'react';
import { Upload, FileText, CheckCircle2, ChevronRight, AlertCircle, Sparkles, Download, Copy, RefreshCw } from 'lucide-react';
import { ResumeReport } from '../types';

interface ResumeAnalyzerProps {
  onAddActivity: (act: any) => void;
  token: string | null;
}

export default function ResumeAnalyzer({ onAddActivity, token }: ResumeAnalyzerProps) {
  const [fileName, setFileName] = useState('');
  const [pastedText, setPastedText] = useState('');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<ResumeReport | null>(null);

  // Drag over states
  const [dragActive, setDragActive] = useState(false);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(true);
  };

  const handleDragLeave = () => {
    setDragActive(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      setFileName(file.name);
      // Read simple text files or mock extract
      const r = new FileReader();
      r.onload = (evt) => {
        if (evt.target?.result) {
          setPastedText(evt.target.result as string);
        }
      };
      r.readAsText(file);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setFileName(file.name);
      const r = new FileReader();
      r.onload = (evt) => {
        if (evt.target?.result) {
          setPastedText(evt.target.result as string);
        }
      };
      r.readAsText(file);
    }
  };

  const runAnalysis = async () => {
    if (!pastedText.trim()) return;
    setLoading(true);
    setReport(null);

    try {
      const res = await fetch('/api/resume/analyze', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token || 'user-demo-123'}`
        },
        body: JSON.stringify({
          filename: fileName || "Pasted_Resume.txt",
          rawText: pastedText
        })
      });

      if (!res.ok) throw new Error('ATS analyzer parsing failed');
      const data = await res.json();
      setReport(data);
      onAddActivity({
        type: 'Resume Scan',
        title: data.filename,
        date: data.createdAt,
        score: `${data.atsScore}% ATS Score`,
        id: data.id
      });
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  // Triggers client download of the ATS report
  const handleDownload = () => {
    if (!report) return;
    const bodyText = `RESUMEPILOT AI - ATS COMPATIBILITY SCORING REPORT
-------------------------------------------------
File Analyzed: ${report.filename}
Overall ATS Rating: ${report.atsScore}/100
Scan Date: ${new Date(report.createdAt).toLocaleDateString()}

EXECUTIVE SUMMARY:
${report.overallSummary}

CRITICAL MISSING INDUSTRY KEYWORDS:
${report.keywordsMissing.map(k => `- ${k}`).join('\n') || 'None'}

SUGGESTED RECRUITER IMPROVEMENTS:
${report.suggestedImprovements.map((imp, idx) => `${idx + 1}. ${imp}`).join('\n') || 'None'}

Generated by ResumePilot AI. Build your career with confidence.`;

    const blob = new Blob([bodyText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ResumePilot_ATS_Report_${report.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 animate-fade-in pl-1">
      
      {/* View Header wrapper */}
      <div>
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white">ATS Resume Compliance Analyzer</h2>
        <p className="text-xs text-slate-500 dark:text-slate-400">Match your resume metadata against modern parsing models to fix structural gaps.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-12">
        {/* Left Form column */}
        <div className="lg:col-span-6 space-y-4">
          <div className="p-6 bg-white dark:bg-[#12141C] border border-slate-200/80 dark:border-slate-800 rounded-2xl space-y-5">
            <h3 className="text-sm font-bold uppercase tracking-wider text-slate-400 font-mono">Upload Candidate Package</h3>
            
            {/* Drop Box area */}
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              className={`border-2 border-dashed rounded-xl p-6 text-center transition-all cursor-pointer relative 
                ${dragActive ? 'border-emerald-500 bg-emerald-500/5' : 'border-slate-200 dark:border-slate-800/80 hover:border-slate-300 dark:hover:border-slate-700'}`}
            >
              <input
                type="file"
                id="file-input"
                onChange={handleFileChange}
                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                accept=".txt,.pdf,.docx"
              />
              <div className="space-y-2 pointer-events-none">
                <Upload className="mx-auto text-slate-400" size={32} />
                <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">
                  {fileName ? `File Selected: ${fileName}` : "Drag & Drop Resume File"}
                </p>
                <p className="text-[10px] text-slate-400">
                  Allows PDF, DOCX or standard PLAINTEXT. Parses string metrics instantly.
                </p>
                <button type="button" className="px-3 py-1 bg-slate-100 dark:bg-slate-800 rounded text-[10px] text-slate-500 dark:text-slate-400 mt-1">
                  Browse Workspace Files
                </button>
              </div>
            </div>

            {/* Paste direct text area fallback */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-500 uppercase tracking-widest font-mono">
                Plaintext Clipboard Dump
              </label>
              <textarea
                value={pastedText}
                onChange={e => setPastedText(e.target.value)}
                placeholder="Paste the full plaintext content of your resume here. The parser scans details instantly..."
                rows={9}
                className="w-full text-xs p-3 border rounded-xl font-mono text-slate-900 dark:text-slate-100 bg-slate-50 dark:bg-[#181B26] border-slate-200 dark:border-slate-800 focus:outline-none focus:ring-1 focus:ring-emerald-500"
              />
            </div>

            <button
              onClick={runAnalysis}
              id="analyze-run-btn"
              disabled={loading || !pastedText.trim()}
              className="w-full py-2.5 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-600 disabled:opacity-50 text-white transition-all shadow-md shadow-emerald-500/10 flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <RefreshCw className="animate-spin" size={14} />
                  Calibrating Compatibility Indicators...
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  Execute Recruiter ATS Compliance Scan
                </>
              )}
            </button>
          </div>
        </div>

        {/* Right Details/Results column */}
        <div className="lg:col-span-6">
          {!report && !loading ? (
            <div className="h-full flex flex-col items-center justify-center p-8 bg-white dark:bg-[#12141C] border border-slate-200/80 dark:border-slate-800 rounded-2xl text-center min-h-[350px]">
              <FileText className="text-slate-300 dark:text-slate-700 mb-2" size={40} />
              <p className="text-xs font-semibold text-slate-500 dark:text-slate-400">Compliance score pending analysis</p>
              <p className="text-[10px] text-slate-400 max-w-xs mt-1">
                Enter your file content and hit execute to audit missing keywords, scoring weights, and action items.
              </p>
            </div>
          ) : loading ? (
            <div className="h-full flex flex-col items-center justify-center p-8 bg-white dark:bg-[#12141C] border border-slate-200/80 dark:border-slate-800 rounded-2xl text-center min-h-[350px]">
              <div className="w-12 h-12 rounded-full border-4 border-slate-100 dark:border-slate-800 border-t-emerald-500 animate-spin mb-4" />
              <p className="text-xs font-bold text-slate-700 dark:text-slate-300">Auditing ATS compatibility weights...</p>
              <p className="text-[10px] text-zinc-400 mt-1 max-w-xs">
                Mapping resumes parameters using Google Gemini models. Grading semantic structural headers, credentials, and matching industry tags.
              </p>
            </div>
          ) : (
            <div className="p-6 bg-white dark:bg-[#12141C] border border-slate-200/80 dark:border-slate-800 rounded-2xl space-y-6 animate-fade-in">
              <div className="flex items-center justify-between">
                <span className="text-sm font-bold uppercase tracking-wider text-slate-400 font-mono">Scan Results Ledger</span>
                <button
                  onClick={handleDownload}
                  className="px-2.5 py-1 text-[10px] bg-slate-50 hover:bg-slate-100 dark:bg-slate-800 dark:hover:bg-slate-700 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 rounded-md font-bold flex items-center gap-1.5"
                >
                  <Download size={12} />
                  Download ATS Report
                </button>
              </div>

              {/* Scoring Dial Gauge */}
              <div className="flex items-center gap-5 p-4 rounded-xl bg-slate-50 dark:bg-slate-900/60 border border-slate-100 dark:border-slate-800">
                <div className="relative flex items-center justify-center w-24 h-24 flex-shrink-0">
                  {/* Gauge SVG */}
                  <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                    <path
                      className="text-slate-200 dark:text-slate-800"
                      strokeWidth="2.5"
                      stroke="currentColor"
                      fill="none"
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    />
                    <path
                      className={`${report.atsScore >= 80 ? 'text-emerald-500' : report.atsScore >= 60 ? 'text-amber-500' : 'text-rose-500'}`}
                      strokeDasharray={`${report.atsScore}, 100`}
                      strokeWidth="2.5"
                      strokeLinecap="round"
                      stroke="currentColor"
                      fill="none"
                      d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    />
                  </svg>
                  <div className="absolute flex flex-col items-center">
                    <span className="text-xl font-bold font-mono text-slate-800 dark:text-white leading-none">
                      {report.atsScore}
                    </span>
                    <span className="text-[8px] text-slate-400 uppercase tracking-widest font-semibold mt-1">
                      Score
                    </span>
                  </div>
                </div>

                <div className="space-y-1 min-w-0">
                  <p className="text-xs font-bold text-slate-800 dark:text-slate-200">Compatibility: {report.atsScore >= 80 ? 'Highly Optimised' : report.atsScore >= 60 ? 'Moderate Compliance' : 'Risk of Auto-rejection'}</p>
                  <p className="text-[10px] text-slate-400 leading-relaxed">
                    Recruiter models recommend a minimum grade of <span className="font-bold text-slate-700 dark:text-slate-300">75%</span> to pass screening filters for corporate microservice architectural roles.
                  </p>
                </div>
              </div>

              {/* Narratives summary */}
              <div className="space-y-1.5">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono">Executive CV Summary</span>
                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed bg-slate-50/50 dark:bg-slate-900/30 p-3 rounded-xl border border-dotted border-slate-200 dark:border-slate-800">
                  {report.overallSummary}
                </p>
              </div>

              {/* Missing keywords tags */}
              <div className="space-y-2">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono block">Missing Recruiter Keywords ({report.keywordsMissing.length})</span>
                <div className="flex flex-wrap gap-1.5">
                  {report.keywordsMissing.map((key, i) => (
                    <span key={i} className="px-2 py-0.5 text-[10px] font-mono font-medium rounded-full border border-rose-500/10 bg-rose-500/5 text-rose-500">
                      {key}
                    </span>
                  ))}
                </div>
              </div>

              {/* Checklists items */}
              <div className="space-y-2">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-mono block">Suggested Checkpoint Actions</span>
                <div className="space-y-2">
                  {report.suggestedImprovements.map((imp, idx) => (
                    <div key={idx} className="flex gap-2.5 p-2.5 rounded-lg bg-slate-50 dark:bg-slate-900/40 border dark:border-slate-800">
                      <AlertCircle className="text-amber-500 flex-shrink-0 mt-0.5" size={14} />
                      <p className="text-xs text-slate-600 dark:text-slate-300 leading-snug">
                        {imp}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

    </div>
  );
}
